#lang sicp
(#%require "Common.rkt")
(#%provide install-drop-package)

(define (install-drop-package)
  (install-rational-package)
  (install-type-raise-package)
  (install-rectangular-package)
  (install-polar-package)
  (install-complex-package)
  (install-scheme-number-package)
  (define real-part (get 'real-part '(complex)))
  (define type-tower (list (cons (cons 'complex 'real)
                                 (lambda (x)
                                   (make-real
                                    (real-part (contents x)))))
                           (cons (cons 'real 'rational)
                                 (lambda (x)
                                   (make-rational (round (contents x)) 1)))
                           (cons (cons 'rational 'integer)
                                 (lambda (x)
                                   (apply-generic 'numer x)))))
  (define (project n)
    (define (p n tower)
      (if (null? tower)
          n
          (let ((level (car tower)))
            (if (eq? (type-tag n) (caar level))
                ((cdr level) n)
                (p n (cdr tower))))))
    (p n type-tower))

  (define raise-number (get 'raise 'number))
  (define (drop n)
    (let ((dn (project n)))
      (cond ((eq? (type-tag n) (type-tag dn)) n) ; 类型相同，说明不可继续 drop 了
            ((apply-generic 'equ? n (raise-number dn)) (drop dn))
            (else n))))
  
  (put 'drop 'project project)
  (put 'drop 'number drop)
  "drop done")
(install-drop-package)
(define (raise n)
  ((get 'raise 'number) n))
(define (drop n)
  ((get 'drop 'number) n))
(define (project n)
  ((get 'drop 'project) n))

(raise (raise (make-rational 1 1)))
(project (make-complex-from-real-imag 1 0))
(raise (make-real 1))
(apply-generic 'equ? (make-real 1) (make-real 2))
(project (make-complex-from-real-imag 1 0))
(define c1 (make-complex-from-real-imag 1 0))
(define r1 (make-real 1))
(drop (make-complex-from-real-imag 1 0))
