#lang sicp
(#%require "Common.rkt")
(#%provide install-drop-package)

(define (install-drop-package)
  (install-rational-package)
  (install-type-raise-package)
  (install-rectangular-package)
  (install-polar-package)
  (install-complex-package)
  (install-scheme-number-package)

  (define real-part (get 'real-part '(complex)))
  (define type-tower (list (cons (cons 'complex 'real)
                                 (lambda (x)
                                   (real-part (contents x))))
                           (cons (cons 'real 'rational)
                                 (lambda (x)
                                   (make-rational (round x) 1)))
                           (cons (cons 'rational 'integer)
                                 (lambda (x)
                                   (numer x)))))
  (define (project n)
    (define (p n tower)
      (if (null? tower)
          n
          (let ((level (car tower)))
            (if (eq? (type-tag n) (caar level))
                ((cdr level) n)
                (p n (cdr tower))))))
    (p n type-tower))

  (define raise-number (get 'raise 'number))
  (define (drop n)
    (let ((dn (project n)))
      (if (apply-generic 'eq? n (raise-number dn))
          (drop dn)
          n)))
  (put 'drop 'number drop)
  "drop done")
(install-drop-package)
(define (raise n)
  ((get 'raise 'number) n))
(define (drop n)
  ((get 'drop 'number) n))

(raise (raise (make-rational 1 1)))
(drop (make-complex-from-real-imag 1 0))
