#lang sicp
; queue 的操作
(define (make-queue) (cons '() '()))
(define (front-ptr queue) (car queue))
(define (rear-ptr queue) (cdr queue))
(define (set-front-ptr! queue item)
  (set-car! queue item))
(define (set-rear-ptr! queue item)
  (set-cdr! queue item))
(define (empty-queue? queue)
  (null? (front-ptr queue)))
(define (front-queue queue)
  (if (empty-queue? queue)
      (error "FRONT called with an empty queue" queue)
      (car (front-ptr queue))))
(define (insert-queue! queue item)
  (let ((new-pair (cons item '())))
    (cond ((empty-queue? queue)
           (set-front-ptr! queue new-pair)
           (set-rear-ptr! queue new-pair)
           queue)
          (else
           (set-cdr! (rear-ptr queue) new-pair)
           (set-rear-ptr! queue new-pair)
           queue))))

(define (delete-queue! q)
  (cond ((empty-queue? q)
         (error "DELETE! called with an empty queue" q))
        (else
         (set-front-ptr! q (cdr (front-ptr q)))
         q)))

(define (call-each procedures)
  (if (null? procedures)
      'done
      (begin
        ((car procedures))
        (call-each (cdr procedures)))))

(define (get-signal wire)
  (wire 'get-signal))

(define (set-signal! wire new-value)
  ((wire 'set-signal!) new-value))

(define (add-action! wire action-procedure)
  ((wire 'add-action!) action-procedure))

(define (make-wire)
  (let ((signal-value 0)
        (action-procedures '()))
    (define (set-my-signal! new-value)
      (if (not (= signal-value new-value))
          (begin (set! signal-value new-value)
                 (call-each action-procedures))
          'done))

    (define (accept-action-procedure! proc)
      (set! action-procedures (cons proc action-procedures))
      (proc))

    (define (dispatch m)
      (cond ((eq? m 'get-signal) signal-value)
            ((eq? m 'set-signal!) set-my-signal!)
            ((eq? m 'add-action!) accept-action-procedure!)
            (else (error "Unknown operation -- WIRE" m))))
    dispatch))

(define (segment-time s) (car s))
(define (segment-queue s) (cdr s))
(define (make-time-segment time queue)
  (cons time queue))
(define (make-agenda) (list 0))
(define (current-time agenda) (car agenda))
(define (set-current-time! agenda time)
  (set-car! agenda time))
(define (segments agenda) (cdr agenda))
(define (set-segments! agenda segments)
  (set-cdr! agenda segments))
(define (first-segment agenda) (car (segments agenda)))
(define (rest-segments agenda) (cdr (segments agenda)))
(define (empty-agenda? agenda)
  (null? (segments agenda)))

(define (add-to-agenda! time action agenda)
  (define (belongs-before? segments)
    (or (null? segments)
        (< time (segment-time (car segments)))))
  (define (make-new-time-segment time action)
    (let ((q (make-queue)))
      (insert-queue! q action)
      (make-time-segment time q)))
  (define (add-to-segments! segments)
    (if (= (segment-time (car segments)) time)
        (insert-queue! (segment-queue (car segments))
                       action)
        (let ((rest (cdr segments)))
          (if (belongs-before? rest)
              (set-cdr!
               segments
               (cons (make-new-time-segment time action)
                     (cdr segments)))
              (add-to-segments! rest)))))
  (let ((segments (segments agenda)))
    (if (belongs-before? segments)
        (set-segments!
         agenda
         (cons (make-new-time-segment time action)
               segments))
        (add-to-segments! segments))))

(define the-agenda (make-agenda))
(define inverter-delay 1)
(define and-gate-delay 1)
(define or-gate-delay 5)

(define (inverter input output)
  (define (invert-input)
    (let ((new-value (logical-not (get-signal input))))
      (after-delay inverter-delay
                   (lambda ()
                     (set-signal! output new-value)))))
  (add-action! input invert-input)
  'ok)

(define (logical-not s)
  (cond ((= s 0) 1)
        ((= s 1) 0)
        (else (error "Invilid signal" s))))

(define (logical-and a b)
  (cond ((and (= a 1) (= b 1)) 1)
        (else 0)))

(define (logical-or a b)
  (cond ((and (= a 0) (= b 0)) 0)
        ((or (= a 1) (= b 1)) 1)
        (else (error "Invilid signal" a b))))

(define (and-gate a1 a2 output)
  (define (and-action-procedure)
    (let ((new-value
           (logical-and (get-signal a1) (get-signal a2))))
      (after-delay and-gate-delay
                   (lambda ()
                     (set-signal! output new-value)))))
  (add-action! a1 and-action-procedure)
  (add-action! a2 and-action-procedure)
  'ok)

; 练习 3.28
(define (or-gate a1 a2 output)
  (define (or-action-procedure)
    (let ((new-value
           (logical-or (get-signal a1) (get-signal a2))))
      (after-delay or-gate-delay
                   (lambda ()
                     (set-signal! output new-value)))))
  (add-action! a1 or-action-procedure)
  (add-action! a2 or-action-procedure)
  'ok)

(define (after-delay delay action)
  (add-to-agenda! (+ delay (current-time the-agenda))
                  action
                  the-agenda))

(define (first-agenda-item agenda)
  (if (empty-agenda? agenda)
      (error "Agenda is empty -- FIRST-AGENDA-ITEM")
      (let ((first-seg (first-segment agenda)))
        (set-current-time! agenda (segment-time first-seg))
        (front-queue (segment-queue first-seg)))))

(define (remove-first-agenda-item! agenda)
  (let ((q (segment-queue (first-segment agenda))))
    (delete-queue! q)
    (if (empty-queue? q)
        (set-segments! agenda (rest-segments agenda)))))

(define (propagate)
  (if (empty-agenda? the-agenda)
      'done
      (let ((first-item (first-agenda-item the-agenda)))
        (first-item)
        (remove-first-agenda-item! the-agenda)
        (propagate))))

(define (probe name wire)
  (add-action! wire
               (lambda ()
                 (newline)
                 (display name)
                 (display " ")
                 (display (current-time the-agenda))
                 (display " New-value = ")
                 (display (get-signal wire))
                 (newline))))

;(define a (make-wire))
;(define b (make-wire))
;(define c (make-wire))
;
;(define d (make-wire))
;(define e (make-wire))
;(define s (make-wire))
;
;(or-gate a b d)
;(and-gate a b c)
;(inverter c e)
;(and-gate d e s)

(define (half-adder a b s c)
  (let ((d (make-wire))
        (e (make-wire)))
    (inverter c e)
    (and-gate d e s)
    (or-gate a b d)
    (and-gate a b c)
    'ok))

(define (full-adder a b c-in sum c-out)
  (let ((s (make-wire))
        (c1 (make-wire))
        (c2 (make-wire)))
    (half-adder b c-in s c1)
    (half-adder a s sum c2)
    (or-gate c1 c2 c-out)
    'ok))
;
;(let ((input-1 (make-wire))
;      (input-2 (make-wire))
;      (sum (make-wire))
;      (carry (make-wire)))
;  (probe 'carry carry)
;  (probe 'sum sum)
;  (half-adder input-1 input-2 sum carry)
;  (set-signal! input-1 1)
;  (propagate)
;  (set-signal! input-2 1)
;  (propagate))

; 练习 3.29
; a || b 等价于 !(!a && !b)
(define (or-gate-3.29 a b output)
  (let ((a1 (make-wire))
        (b1 (make-wire))
        (c1 (make-wire)))
    (inverter a a1)
    (inverter b b1)
    (and-gate a1 b1 c1)
    (inverter c1 output)
    'ok))
(display "练习 3.29")

(let ((input-1 (make-wire))
      (input-2 (make-wire))
      (output-1 (make-wire)))
  (or-gate-3.29 input-1 input-2 output-1)
  (probe 'input-1 input-1)
  (probe 'input-2 input-2)
  (probe 'output-1 output-1)
  (propagate)
  (set-signal! input-1 0)
  (set-signal! input-2 0)
  (propagate))
;  (set-signal! input-1 0)
;  (propagate)
;  (set-signal! input-2 0)
;  (propagate)
;  (set-signal! input-1 1)
;  (propagate)
;  (set-signal! input-2 0)
;  (propagate)
;  (set-signal! input-1 0)
;  (propagate)
;  (set-signal! input-2 1)
;  (propagate))
  ;(set-signal! input-2 0)
  ;(propagate))
;(let ((input-1 (make-wire))
;      (input-2 (make-wire))
;      (output-1 (make-wire)))
;  (probe 'input-1 input-1)
;  (probe 'input-2 input-2)
;  (probe 'output-1 output-1)
;  (or-gate-3.29 input-1 input-2 output-1)
;  (propagate)
;  (set-signal! input-1 1))

; 练习 3.30
(define (ripple-carry-adder a1 a2 a3 b1 b2 b3 c-out s1 s2 s3)
  (let ((c (make-wire))
        (c1 (make-wire))
        (c2 (make-wire)))
    (full-adder a3 b3 c s3 c2)
    (full-adder a2 b2 c2 s2 c1)
    (full-adder a1 b1 c1 s1 c-out)))

(let ((a1 (make-wire))
      (a2 (make-wire))
      (a3 (make-wire))
      (b1 (make-wire))
      (b2 (make-wire))
      (b3 (make-wire))
      (s1 (make-wire))
      (s2 (make-wire))
      (s3 (make-wire))
      (c (make-wire))
      (c-out (make-wire)))
  (probe 's1 s1)
  (probe 's2 s2)
  (probe 's3 s3)
  (probe 'c-out c-out)
  (ripple-carry-adder a1 a2 a3 b1 b2 b3 c-out s1 s2 s3)
  (set-signal! a3 1)
  (set-signal! b3 1)
  (set-signal! a2 1)
  (set-signal! b2 1)
  (set-signal! a1 1)
  (set-signal! b1 1)
  (propagate)
  (display (list (get-signal c-out)
                 (get-signal s1)
                 (get-signal s2)
                 (get-signal s3)
                 )))

(let ((a (make-wire))
      (b (make-wire)))
  (inverter a b)
  (set-signal! a 0)
  (after-delay 10
               (lambda ()
                 (display (list (get-signal a)
                                (get-signal b)))))
  (propagate))

; 需要用 propagate 驱动一下

; 练习 3.31
; 为什么在 make-wire 里定义的内部过程 accept-action-procedure!
; 当一个新动作加入时，这一过程应立即执行
; 猜测与时序有关
; 半加器 a = 1 b = 0 时，立即执行与不立即执行得到了不同的结果
; 除非设置门电路时，必须按一定的次序，否则就需要加上立即执行的动作

(newline)
(display "练习3.31")
(newline)
(let ((a (make-wire))
      (b (make-wire))
      (s (make-wire))
      (c (make-wire)))
  (half-adder a b s c)
  (set-signal! a 1)
  (set-signal! b 0)
  (propagate)
  (display (list "s :" (get-signal s) "c :" (get-signal c))))