#lang sicp

; 队列的表示
(define (front-ptr queue) (car queue))
(define (rear-ptr queue) (cdr queue))
(define (set-front-ptr! queue item) (set-car! queue item))
(define (set-rear-ptr! queue item) (set-cdr! queue item))
(define (empty-queue? queue) (null? (front-ptr queue)))
(define (make-queue) (cons '() '()))

(define (front-queue queue)
  (if (empty-queue? queue)
      (error "FRONT called with an empty queue" queue)
      (car (front-ptr queue))))

(define (insert-queue! queue item)
  (let ((new-pair (cons item '())))
    (cond ((empty-queue? queue)
           (set-front-ptr! queue new-pair)
           (set-rear-ptr! queue new-pair)
           queue)
          (else
           (set-cdr! (rear-ptr queue) new-pair)
           (set-rear-ptr! queue new-pair)
           queue))))

(define (delete-queue! queue)
  (cond ((empty-queue? queue)
         (error "DELETE! called with an empty queue" queue))
        (else
         (set-front-ptr! queue (cdr (front-ptr queue)))
         queue)))

; 练习 3.22
(define (print-queue queue)
  (display (front-ptr queue)))
;(define (print-queue queue)
;  (define (iter p q)
;    (display p)
;    (if (not (eq? p q))
;        (iter (cdr p) q)))
;  (iter (front-ptr queue) (rear-ptr queue)))

(let ((q (make-queue)))
  (insert-queue! q 'a)
  (insert-queue! q 'b)
  (insert-queue! q 'c)
  (insert-queue! q 'd)
  (insert-queue! q 'e)
  (print-queue q))

; 练习 3.23
(define (make-queue-v2)
  (let ((front-ptr '())
        (rear-ptr '()))
    (define (empty-queue?) (null? front-ptr))
    (define (set-front-ptr! item) (set! front-ptr item))
    (define (set-rear-ptr! item) (set! rear-ptr item))
    (define (front-queue)
      (if (empty-queue?)
          (error "FRONT called witch an empty queue" front-ptr)
          (car front-ptr)))
    (define (insert item)
      (let ((new-pair (cons item '())))
        (cond ((empty-queue?)
               (set-front-ptr! new-pair)
               (set-rear-ptr! new-pair)
               front-ptr)
              (else
               (set-cdr! rear-ptr new-pair)
               (set-rear-ptr! new-pair)
               front-ptr))))
    (define (delete)
      (if (empty-queue?)
          (error "FRONT called with an empty queue" front-ptr)
          (set-front-ptr! (cdr front-ptr))))
    (define (print)
      (display front-ptr))
    (define (dispatch m)
      (cond ((eq? m 'insert) insert)
            ((eq? m 'delete) (delete))
            ((eq? m 'front) front-queue)
            ((eq? m 'empty?) (empty-queue?))
            ((eq? m 'print) (print))))
    dispatch))
(let ((q (make-queue-v2)))
  ((q 'insert) 'a)
  ((q 'insert) 'b)
  (q 'print)
  (q 'delete)
  (q 'print)
  (q 'delete)
  (q 'print)
  (q 'empty?))

; 练习 3.23
(define (make-deque)
  (cons '() '()))

(define (left-ptr-deque deque) (car deque))
(define (rear-ptr-deque deque) (cdr deque))

(define (empty-deque? deque)
  (null? (left-ptr-deque deque)))

(define (front-deque deque)
  (if (empty-deque? deque)
      (error "FRONT called with an empty deque" (left-ptr-deque deque))
      (cdr (left-ptr-deque deque))))

(define (rear-deque deque)
  (if (empty-deque? deque)
      (error "REAR called with an empty deque" (rear-ptr-deque deque))
      (cdr (rear-ptr-deque deque))))

(define (make-deque-node item)
  (cons (cons '() '()) item))

(define (deque-back-ptr node)
  (caar node))
(define (deque-front-ptr node)
  (cadr node))
(define (node-data node)
  (cdr node))

(define (front-insert-deque! deque item)
  (let ((new-node (make-deque-node item)))
    (cond ((empty-deque? deque)
           (set! (left-ptr-deque deque) new-node)
           (set! (rear-ptr-deque deque) new-node))
          (else
           (set! (back-ptr new-node) (left-ptr-deque deque))
           (set! (deque-front-ptr (left-ptr-deque deque)) new-node)
           (set! (left-ptr-deque deque) new-node)))))

(define (rear-insert-deque! deque item)
  'none)
(define (front-delete-deque! deque)
  'none)
(define (rear-delete-deque! deque)
  'none)