#lang sicp

; sets as binary tree

(define (entry tree) (car tree))
(define (left-branch tree) (cadr tree))
(define (right-branch tree) (caddr tree))
(define (make-tree entry left right)
  (list entry left right))

(define (element-of-set? x s)
  (cond ((null? s) false)
        ((= x (entry s)) true)
        ((< x (entry s))
         (element-of-set? x (left-branch s)))
        ((> x (entry s))
         (element-of-set? x (right-branch s)))))

(define t1 (make-tree 7
                      (make-tree 3
                                 (make-tree 1 '() '())
                                 (make-tree 5 '() '()))
                      (make-tree 9
                                 '()
                                 (make-tree 11 '() '()))))
(element-of-set? 1 t1)
(element-of-set? 2 t1)
(element-of-set? 3 t1)
(element-of-set? 4 t1)
(element-of-set? 5 t1)
(element-of-set? 6 t1)

(define (adjoin-set x s)
  (cond ((null? s) (make-tree x '() '()))
        ((= x (entry s)) s)
        ((< x (entry s))
         (make-tree (entry s)
                    (adjoin-set x (left-branch s))
                    (right-branch s)))
        ((> x (entry s))
         (make-tree (entry s)
                    (left-branch s)
                    (adjoin-set x (right-branch s))))))

(define t2 '())

(set! t2 (adjoin-set 1 t2))
(set! t2 (adjoin-set 2 t2))
(set! t2 (adjoin-set 3 t2))
(set! t2 (adjoin-set 4 t2))
(set! t2 (adjoin-set 5 t2))
(set! t2 (adjoin-set 6 t2))
(set! t2 (adjoin-set 7 t2))
;(set! t2 (adjoin-set 1 t2))
;(set! t2 (adjoin-set 5 t2))
;(set! t2 (adjoin-set 11 t2))
;(set! t2 (adjoin-set 12 t2))
;(set! t2 (adjoin-set 8 t2))

(define (tree->list-v1 tree)
  (display 'tree->list-v1)
  (newline)
  (if (null? tree)
      '()
      (append (tree->list-v1 (left-branch tree))
              (cons (entry tree)
                    (tree->list-v1 (right-branch tree))))))

(define (tree->list-v2 tree)
  (define (copy-to-list tree result-list)
    (display 'copy-to-list)
    (newline)
    (if (null? tree)
        result-list
        (copy-to-list (left-branch tree)
                      (cons (entry tree)
                            (copy-to-list (right-branch tree)
                                          result-list)))))
  (copy-to-list tree '()))
(tree->list-v1 t2)
(tree->list-v2 t2)

; 练习 2.64
(define (list->tree elements)
  (car (partial-tree elements (length elements))))

(define (partial-tree elts n)
  (if (= n 0)
      (cons '() elts)
      (let ((left-size (quotient (- n 1) 2)))
        (let ((left-result (partial-tree elts left-size)))
          (let ((left-tree (car left-result))
                (non-left-elts (cdr left-result))
                (right-size (- n (+ left-size 1))))
            (let ((this-entry (car non-left-elts))
                  (right-result (partial-tree (cdr non-left-elts)
                                              right-size)))
              (let ((right-tree (car right-result))
                    (remaining-elts (cdr right-result)))
                (cons (make-tree this-entry left-tree right-tree)
                      remaining-elts))))))))
(list->tree '(1 2 3 4 5 6 7))