#lang sicp

; 队列的表示
(define (front-ptr queue) (car queue))
(define (rear-ptr queue) (cdr queue))
(define (set-front-ptr! queue item) (set-car! queue item))
(define (set-rear-ptr! queue item) (set-cdr! queue item))
(define (empty-queue? queue) (null? (front-ptr queue)))
(define (make-queue) (cons '() '()))

(define (front-queue queue)
  (if (empty-queue? queue)
      (error "FRONT called with an empty queue" queue)
      (car (front-ptr queue))))

(define (insert-queue! queue item)
  (let ((new-pair (cons item '())))
    (cond ((empty-queue? queue)
           (set-front-ptr! queue new-pair)
           (set-rear-ptr! queue new-pair)
           queue)
          (else
           (set-cdr! (rear-ptr queue) new-pair)
           (set-rear-ptr! queue new-pair)
           queue))))

(define (delete-queue! queue)
  (cond ((empty-queue? queue)
         (error "DELETE! called with an empty queue" queue))
        (else
         (set-front-ptr! queue (cdr (front-ptr queue)))
         queue)))

; 练习 3.22
(define (print-queue queue)
  (display (front-ptr queue)))
;(define (print-queue queue)
;  (define (iter p q)
;    (display p)
;    (if (not (eq? p q))
;        (iter (cdr p) q)))
;  (iter (front-ptr queue) (rear-ptr queue)))

(let ((q (make-queue)))
  (insert-queue! q 'a)
  (insert-queue! q 'b)
  (insert-queue! q 'c)
  (insert-queue! q 'd)
  (insert-queue! q 'e)
  (print-queue q))

; 练习 3.23
(define (make-queue-v2)
  (let ((front-ptr '())
        (rear-ptr '()))
    (define (empty-queue?) (null? front-ptr))
    (define (set-front-ptr! item) (set! front-ptr item))
    (define (set-rear-ptr! item) (set! rear-ptr item))
    (define (front-queue)
      (if (empty-queue?)
          (error "FRONT called witch an empty queue" front-ptr)
          (car front-ptr)))
    (define (insert item)
      (let ((new-pair (cons item '())))
        (cond ((empty-queue?)
               (set-front-ptr! new-pair)
               (set-rear-ptr! new-pair)
               front-ptr)
              (else
               (set-cdr! rear-ptr new-pair)
               (set-rear-ptr! new-pair)
               front-ptr))))
    (define (delete)
      (if (empty-queue?)
          (error "FRONT called with an empty queue" front-ptr)
          (set-front-ptr! (cdr front-ptr))))
    (define (print)
      (display front-ptr))
    (define (dispatch m)
      (cond ((eq? m 'insert) insert)
            ((eq? m 'delete) (delete))
            ((eq? m 'front) front-queue)
            ((eq? m 'empty?) (empty-queue?))
            ((eq? m 'print) (print))))
    dispatch))
(let ((q (make-queue-v2)))
  ((q 'insert) 'a)
  ((q 'insert) 'b)
  (q 'print)
  (q 'delete)
  (q 'print)
  (q 'delete)
  (q 'print)
  (q 'empty?))

; 练习 3.23
(define (make-deque)
  (cons (cons '(a) '(b))
        (cons '(c) '(d))))

(define (left-front-ptr deque) (caar deque))
(define (left-rear-ptr deque) (cdar deque))
(define (right-front-ptr deque) (cadr deque))
(define (right-rear-ptr deque) (cddr deque))

(define (empty-deque? deque)
  (null? (left-front-ptr deque)))

(define (front-deque deque)
  (if (empty-deque? deque)
      (error "FRONT called with an empty deque" (left-front-ptr deque))
      (car (left-front-ptr deque))))

(define (rear-deque deque)
  (if (empty-deque? deque)
      (error "REAR called with an empty deque" (left-rear-ptr deque))
      (car (right-front-ptr deque))))
;
;(define (front-insert-deque! deque item)
;  (let ((new-pair (cons item '())))
;    (cond ((empty-queue? deque)
;           (set! (left-front-ptr deque) new-pair)
;           (set! (left-rear-ptr deque) new-pair)
;           (set! (right-front-ptr deque) new-pair)
;           (set! (right-rear-ptr deque) new-pair)
;           deque)
;          (else
;           
;           deque))))
