#lang sicp
(#%require "Figure4.interp.rkt")

(display genv)
(eval '(+ 1 2 3) genv)
(eval '(cons 1 2) genv)
(eval '(* 1 2 3) genv)
(eval '(- 1 2 3) genv)
(eval '(car (list 1 2 3)) genv)
(eval '(car (cdr '(1 2 3))) genv)
(eval '(define (f x)
         (if (<= x 2)
             1
             (+ (f (- x 1)) (f (- x 2))))) genv)
(eval '(list 1 2 3) genv)
(eval '(define (map proc args)
         (if (null? args)
             '()
             (cons (proc (car args))
                   (map proc (cdr args)))))
      genv)
(eval 'map genv)
(eval '(define (inc x) (+ x 1)) genv)
(eval '(map inc (list 1 2 3)) genv)
(newline)
(eval '((lambda ()
          (display 1)
          2222)) genv)
(newline)
(display "let 语法糖")
(eval '(let ((a 1)
             (b 2)
             (c 3))
         (* a b c)) genv)
(eval '(let ()
         (display 1)
         (display 2)
         3333) genv)
(eval '(let ((a (+ 1 2))
             (b (+ 2 3))
             (c (+ (+ 1 2 3))))
         (let ((d (+ 1 2))
               (e (let ((a 10)
                        (b 20))
                    (+ a b))))
           (display (list a b c d e))
           (* a b c d e))) genv)
(eval '((lambda (x y)
          (display (list x y))
          (+ x y)) 1 2) genv)

(eval '(let ((a (lambda (x) (+ x x)))
             (b (lambda (x) (* x x))))
         (a (b 10))) genv)
(eval '(let ((f false)
             (g false))
         (let ((a (lambda (x) (+ x x)))
               (b (lambda (x) (* x x))))
           (set! f a)
           (set! g b)
           (f (g 10)))) genv)
(eval '(define (sum x y)
         (define (f x)
           (+ x 1))
         (define (g x)
           (* x 2))
         (f (g (+ x y)))) genv)
(eval '(sum 1 2) genv)
(display "处理 let*")
(newline)
(eval (let*->nested-lets '(let* ((a 1)
                                 (b (+ a 1)))
                            (+ a b))) genv)
(define code (let*->nested-lets '(let* ((a 2)
                                        (g (lambda (x)
                                             (+ x a))))
                                   (+ a (g 10)))))
(eval code genv)
(define c1 '(let* ((a 1))
              (let* ((b 1)
                     (c 1))
                (+ a b c))
              (let* ((a 2)
                     (b 3))
                (+ a b))))
(define r1 (let*->nested-lets c1))
(eval r1 genv)

(define c2 '(let* ((a (let* ((b 1)
                             (c (+ b 1)))
                        (+ b c)))
                   (d (* a a)))
              (* a d)))
(define r2 (let*->nested-lets c2))
(eval r2 genv)
